In [23]:
import pandas as pd

In [24]:

df = pd.read_csv("/Users/roy/Desktop/SPIDE/Phase2/csvs/OverallPlayerStats.csv")

In [25]:
df.columns

df = df[df.PTS != "PTS"]
df["TRB"] = df["TRB"].astype(float)
df["PTS"] = df["PTS"].astype(float)
df["AST"] = df["AST"].astype(float)

df["COMBO"] = (df["PTS"])+(df["AST"])+(df["TRB"])
df = df.sort_values(by=["3P"],ascending=False)
PTS_df = df.sort_values(by=["3P"],ascending=False)


df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'COMBO'],
      dtype='object')

In [26]:
grouped_teams = df.groupby('Tm')
columns_to_include = ['Tm' ,'Player','G','MP','3P','TRB', 'AST','PTS', 'COMBO']
# Create separate DataFrames for each team
team_dataframes = {}
for team_name, group_data in grouped_teams:
    team_dataframes[team_name] = group_data.loc[:,columns_to_include]
df=df.loc[:,columns_to_include].head(30)
print(df)
# Access each team's DataFrame using the team name

      Tm             Player   G    MP   3P  TRB   AST   PTS  COMBO
158  GSW      Stephen Curry  74  32.7  4.8  4.5   5.1  26.4   36.0
177  DAL        Luka Dončić  70  37.5  4.1  9.2   9.8  33.9   52.9
436  NOP        CJ McCollum  66  32.7  3.6  4.3   4.6  20.0   28.9
176  NYK   Donte DiVincenzo  81  29.1  3.5  3.7   2.7  15.5   21.9
665  GSW      Klay Thompson  77  29.7  3.5  3.3   2.3  17.9   23.5
625  POR    Anfernee Simons  46  34.4  3.4  3.6   5.5  22.6   31.7
34   MEM       Desmond Bane  42  34.4  3.3  4.4   5.5  23.7   33.6
471  CLE   Donovan Mitchell  55  35.3  3.3  5.1   6.1  26.6   37.8
235  LAC        Paul George  74  33.8  3.3  5.2   3.5  22.6   31.3
31   CHO        LaMelo Ball  22  32.3  3.2  5.1   8.0  23.9   37.0
759  ATL         Trae Young  54  36.0  3.2  2.8  10.8  25.7   39.3
420  UTA    Lauri Markkanen  55  33.1  3.2  8.2   2.0  23.2   33.4
297  MIA        Tyler Herro  42  33.5  3.1  5.3   4.5  20.8   30.6
654  BOS       Jayson Tatum  74  35.7  3.1  8.1   4.9  26.9   39.9
77   DET   Bojan Bogdanović  28  32.9  3.1  3.4   2.5  20.2   26.1
687  HOU      Fred VanVleet  73  36.8  3.1  3.8   8.1  17.4   29.3
75   ATL  Bogdan Bogdanović  79  30.4  3.0  3.4   3.1  16.9   23.4
488  NOP    Trey Murphy III  57  29.6  3.0  4.9   2.2  14.8   21.9
325  DAL       Kyrie Irving  58  35.0  3.0  5.0   5.2  25.6   35.8
597  LAL   D'Angelo Russell  76  32.7  3.0  3.1   6.3  18.0   27.4
431  PHI       Tyrese Maxey  70  37.5  3.0  3.7   6.2  25.9   35.8
392  MIL     Damian Lillard  73  35.3  3.0  4.4   7.0  24.3   35.7
214  SAC       De'Aaron Fox  74  35.9  2.9  4.6   5.6  26.6   36.8
56   MIL      Malik Beasley  79  29.6  2.8  3.7   1.4  11.3   16.4
274  IND  Tyrese Haliburton  69  32.2  2.8  3.9  10.9  20.1   34.9
580  MIA    Duncan Robinson  68  28.0  2.8  2.5   2.8  12.9   18.2
567  TOR  Immanuel Quickley  38  33.3  2.8  4.8   6.8  18.6   30.2
593  CHO       Terry Rozier  30  35.5  2.8  3.9   6.6  23.2   33.7
721  BOS      Derrick White  73  32.6  2.7  4.2   5.2  15.2   24.6
93   BRK      Mikal Bridges  82  34.8  2.7  4.5   3.6  19.6   27.7

In [27]:
df.loc[:,columns_to_include].head(30)
x=df["Player"][0:31]
print(str(list(x)).replace("'",''))

[Stephen Curry, Luka Dončić, CJ McCollum, Donte DiVincenzo, Klay Thompson, Anfernee Simons, Desmond Bane, Donovan Mitchell, Paul George, LaMelo Ball, Trae Young, Lauri Markkanen, Tyler Herro, Jayson Tatum, Bojan Bogdanović, Fred VanVleet, Bogdan Bogdanović, Trey Murphy III, Kyrie Irving, "DAngelo Russell", Tyrese Maxey, Damian Lillard, "DeAaron Fox", Malik Beasley, Tyrese Haliburton, Duncan Robinson, Immanuel Quickley, Terry Rozier, Derrick White, Mikal Bridges]

In [28]:
str(list(team_dataframes["DEN"]["Player"].head(6))).replace("'",'')

'[Michael Porter Jr., Jamal Murray, Kentavious Caldwell-Pope, Reggie Jackson, Nikola Jokić, Justin Holiday]'

In [29]:
team_dataframes["LAL"].head(10)

      Tm             Player   G    MP   3P  TRB  AST   PTS  COMBO
597  LAL   D'Angelo Russell  76  32.7  3.0  3.1  6.3  18.0   27.4
337  LAL       LeBron James  71  35.3  2.1  7.3  8.3  25.7   41.3
573  LAL      Austin Reaves  82  32.1  1.9  4.3  5.5  15.9   25.7
560  LAL     Taurean Prince  78  27.0  1.8  2.9  1.5   8.9   13.3
272  LAL      Rui Hachimura  68  26.9  1.4  4.3  1.2  13.6   19.1
175  LAL  Spencer Dinwiddie  28  24.2  1.3  1.7  2.4   6.8   10.9
574  LAL        Cam Reddish  48  20.5  0.8  2.1  1.0   5.4    8.5
752  LAL     Christian Wood  50  17.4  0.7  5.1  1.0   6.9   13.0
134  LAL       Max Christie  67  14.1  0.6  2.1  0.9   4.2    7.2
748  LAL      Dylan Windler   8   3.5  0.5  0.4  0.8   1.5    2.7

In [30]:
import sqlite3
conn = sqlite3.connect("/Users/roy/Desktop/SPIDE/Phase2/DataBase/NBA_Player_Database.db")
cursor = conn.cursor()

In [31]:
query = 'SELECT * FROM BoxScores where Player = "Domantas Sabonis"'
df = pd.read_sql_query(query, conn)
df

,boxscores_id,BoxScore_ID,Player,MP,FG,FGA,FG%,3P,3PA,3P%,...,PF,PTS,+/-,BoxScore_Type,Token,Home,Away,Date,Team,Opponent
0,2327,202310250UTAVSSAC_G SAC,Domantas Sabonis,32:08,8.0,14.0,0.571,1.0,2.0,0.5,...,3.0,22.0,+5,G,202310250UTAVSSAC,UTA,SAC,20231025,SAC,UTA
1,2343,202310250UTAVSSAC_Q1 SAC,Domantas Sabonis,8:52,1.0,1.0,1.000,0.0,0.0,NaN,...,0.0,2.0,+3,Q1,202310250UTAVSSAC,UTA,SAC,20231025,SAC,UTA
2,2359,202310250UTAVSSAC_Q2 SAC,Domantas Sabonis,7:29,3.0,6.0,0.500,1.0,2.0,0.5,...,0.0,7.0,+4,Q2,202310250UTAVSSAC,UTA,SAC,20231025,SAC,UTA
3,2375,202310250UTAVSSAC_H1 SAC,Domantas Sabonis,16:21,4.0,7.0,0.571,1.0,2.0,0.5,...,0.0,9.0,+7,H1,202310250UTAVSSAC,UTA,SAC,20231025,SAC,UTA
4,2391,202310250UTAVSSAC_Q3 SAC,Domantas Sabonis,9:01,2.0,4.0,0.500,0.0,0.0,NaN,...,1.0,7.0,-1,Q3,202310250UTAVSSAC,UTA,SAC,20231025,SAC,UTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,247033,202404190NOPVSSAC_Q2 SAC,Domantas Sabonis,12:00,1.0,2.0,0.500,0.0,1.0,0.0,...,0.0,2.0,-11,Q2,202404190NOPVSSAC,NOP,SAC,20240419,SAC,NOP
591,247047,202404190NOPVSSAC_H1 SAC,Domantas Sabonis,20:00,4.0,6.0,0.667,0.0,1.0,0.0,...,2.0,10.0,-8,H1,202404190NOPVSSAC,NOP,SAC,20240419,SAC,NOP
592,247061,202404190NOPVSSAC_Q3 SAC,Domantas Sabonis,9:54,2.0,4.0,0.500,0.0,0.0,NaN,...,0.0,6.0,-1,Q3,202404190NOPVSSAC,NOP,SAC,20240419,SAC,NOP
593,247075,202404190NOPVSSAC_Q4 SAC,Domantas Sabonis,11:57,3.0,4.0,0.750,0.0,0.0,NaN,...,2.0,7.0,+2,Q4,202404190NOPVSSAC,NOP,SAC,20240419,SAC,NOP
594,247089,202404190NOPVSSAC_H2 SAC,Domantas Sabonis,21:51,5.0,8.0,0.625,0.0,0.0,NaN,...,2.0,13.0,+1,H2,202404190NOPVSSAC,NOP,SAC,20240419,SAC,NOP